/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JAAS;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

// делаем класс сервлетом - extends HttpServlet
public class App extends HttpServlet {
    public String getGreeting() {
        return "Hello World! Secret!";
    }
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.getWriter().print(getGreeting());
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
